module CommitLogParser
  def commit_list(commit_log)

    # example commit_log generated by
    # `git log --pretty='%H%n%s%n%aN%n%aE%n%at%n%cN%n%cE%n%ct%n' HEAD^..HEAD`

    #  15e8cbd88d68d210953d51c28e26c6b9944a313b
    #  ignore .ruby-version for rvm
    #  Bob Smith
    #  bob@example.com
    #  1367556311
    #  Fred Smith
    #  fred@example.com
    #  1367556311
    #

    record = []
    commits = []
    commit_log.lines.each_with_index do |line|
      line.strip!
      if line.empty?
        c = parse_commit(record)
        commits.push(c)
        record = []
      else
        record.push(line)
      end
    end

    commits
  end

  private

  def parse_commit(record)
    time = Time.at(record[4].to_i)
    author = build_user(record[2], record[3])
    committer = build_user(record[5], record[6])
    build_commit(record[0], author, committer, record[1], time)
  end

  def build_user(name, email)
    {"name" => name, "email" => email}
  end

  def build_commit(sha, author, committer, summary, date)
    {"id" => sha, "author" => author, "committer" => committer, "summary" => summary, "date" => date}
  end
end
