require 'spec_helper'
require 'tddium/commit_log_parser'

describe CommitLogParser do
  class TestClass
    include CommitLogParser
  end

  subject { TestClass.new }

  describe "#commit_list(commit_log)" do
    let(:commit_log) {
      # generated by `git log --pretty='%H%n%s%n%aN%n%aE%n%at%n%cN%n%cE%n%ct%n' HEAD^..HEAD`
      """15e8cbd88d68d210953d51c28e26c6b9944a313b
        ignore .ruby-version for rvm
        Bob Smith
        bob@example.com
        1367556311
        Fred Smith
        fred@example.com
        1367556311
      """
    }

    it "should return a commit list from the commit log" do
      commit = subject.commit_list(commit_log)[0]
      commit["id"].should == "15e8cbd88d68d210953d51c28e26c6b9944a313b"
      commit["summary"].should == "ignore .ruby-version for rvm"
      commit["author"]["name"].should == "Bob Smith"
      commit["author"]["email"].should == "bob@example.com"
      commit["committer"]["name"].should == "Fred Smith"
      commit["committer"]["email"].should == "fred@example.com"
      commit["date"].should == Time.at(1367556311)
    end
  end
end
